# Generated by Django 4.2.4 on 2023-08-17 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0003_alter_savat_vaqt_tanlangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savat',
            name='vaqt',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 8, 33, 30, 727885)),
        ),
        migrations.DeleteModel(
            name='Tanlangan',
        ),
    ]
