# Generated by Django 4.2.4 on 2023-08-17 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0007_savat_arxivda_alter_savat_vaqt_buyurtma'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='summa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='savat',
            name='vaqt',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 9, 57, 20, 81534)),
        ),
    ]
