# Generated by Django 4.2.4 on 2023-08-15 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('asosiy', '0002_mahsulot_ishlab_chiqaruvchi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='asosiy.mahsulot'),
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('sana', models.DateField()),
                ('baho', models.PositiveSmallIntegerField()),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.mahsulot')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.profil')),
            ],
        ),
    ]
