# Generated by Django 4.2.4 on 2023-08-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_tanlangan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tanlangan',
        ),
    ]
