# Generated by Django 4.2.4 on 2023-08-15 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='davlat',
            new_name='vilotay',
        ),
    ]
